### ISSUE TITLE
mlcube-0.0.1: wrong file inside

### ISSUE THREAD

**Issue by sergey-serebryakov** [mlperf/mlcube#151]
Somehow, the [mlcube-0.0.1](https://files.pythonhosted.org/packages/1f/d7/a964a3ca834871a611cfb5d2dfc141c489a5ffa6cd2c16409331d1cf2ae2/mlcube-0.0.1.tar.gz) was packaged with the wrong file.

Error:
```
Traceback (most recent call last):
  File "/tmp/env/bin/mlcube_docker", line 5, in <module>
    from mlcube_docker.__main__ import cli
  File "/tmp/env/lib/python3.8/site-packages/mlcube_docker/__main__.py", line 4, in <module>
    from mlcube.common import mlcube_metadata
ImportError: cannot import name 'mlcube_metadata' from 'mlcube.common' (/tmp/env/lib/python3.8/site-packages/mlcube/common/__init__.py)

```

__Expected__: file name is `mlcube/common/mlcube_metadata.py`
__Observed__: file name is `mlcube/common/mlbox_metadata.py`
__Solution__: the `master` branch contains the right file, will be fixed in the next release.

**Comment by sergey-serebryakov** [comment]
Fixed in release 0.0.2.
